version: "3.9"

services:
  backend:
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    restart: always
#    depends_on:
#      - db
#      - redis
    build:
      context: ..
      dockerfile: test_da/Dockerfile.local
    command: bash ./start-local.sh
    logging:
      driver: "json-file"
      options:
        max-size: 128m
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./deploy:/app/deploy
      - ./:/app

#  redis:
#    container_name: ${COMPOSE_PROJECT_NAME}_redis
#    image: "redis:6.2-alpine"
#    restart: always
#    command: redis-server /usr/local/etc/redis/redis.conf
#    volumes:
#      - ./volumes/redis:/data
#      - ./deploy/redis/redis.conf:/usr/local/etc/redis/redis.conf
#    ports:
#      - "6379:6379"
#
#  db:
#    container_name: ${COMPOSE_PROJECT_NAME}_db
#    image: postgres:15-alpine
#    restart: always
#    command: [ "postgres", "-c", "log_statement=all" ]
#    env_file:
#      - .env
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
#      - ./volumes/postgresql/pg-data:/var/lib/postgresql/data

volumes:
  shop_backend:
#  shop_db:
#  shop_redis:
