"""init

Revision ID: 38b12ea9b2da
Revises: 
Create Date: 2024-01-03 10:28:32.846900

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b12ea9b2da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(), server_default=str(datetime.now()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=str(datetime.now()), onupdate=str(datetime.now())),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('item',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(), server_default=str(datetime.now()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=str(datetime.now()), onupdate=str(datetime.now())),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_item_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('user')
    # ### end Alembic commands ###
